name: Build Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  OUTPUT_FOLDER: "./output"
  
jobs:
  pack-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for deployment
        uses: actions/checkout@v5

      - name: Checkout core_types-format repository
        uses: actions/checkout@v5
        with:
          repository: 0x007E/core_types-format
          path: core_types-format
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout core_types-return repository
        uses: actions/checkout@v5
        with:
          repository: 0x007E/core_types-return
          path: core_types-return
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout hal-common repository
        uses: actions/checkout@v5
        with:
          repository: 0x007E/hal-common
          path: hal-common
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout hal-avr0-twi repository
        uses: actions/checkout@v5
        with:
          repository: 0x007E/hal-avr0-twi
          path: hal-avr0-twi
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout utils-macros repository
        uses: actions/checkout@v5
        with:
          repository: 0x007E/utils-macros
          path: utils-macros
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout utils-systick repository
        uses: actions/checkout@v5
        with:
          repository: 0x007E/utils-systick
          path: utils-systick
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout utils-timerepository
        uses: actions/checkout@v5
        with:
          repository: 0x007E/utils-time
          path: utils-time
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare library package
        run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/core_types/format
          cp -r ./core_types-format/time.h ./${{ env.OUTPUT_FOLDER }}/core_types/format/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/core_types/return
          cp -r ./core_types-return/status.h ./${{ env.OUTPUT_FOLDER }}/core_types/return/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/common
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/common/defines
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/common/enums
          cp -r ./hal-common/defines/TWI_defines.h ./${{ env.OUTPUT_FOLDER }}/hal/common/defines/
          cp -r ./hal-common/enums/TWI_enums.h ./${{ env.OUTPUT_FOLDER }}/hal/common/enums/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/avr0/twi
          cp -r ./hal-avr0-twi/twi.c ./${{ env.OUTPUT_FOLDER }}/hal/avr0/twi/
          cp -r ./hal-avr0-twi/twi.h ./${{ env.OUTPUT_FOLDER }}/hal/avr0/twi/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/utils/macros
          cp -r ./utils-macros/stringify.h ./${{ env.OUTPUT_FOLDER }}/utils/macros/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/utils/systick
          cp -r ./utils-systick/systick.c ./${{ env.OUTPUT_FOLDER }}/utils/systick/
          cp -r ./utils-systick/systick.h ./${{ env.OUTPUT_FOLDER }}/utils/systick/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/utils/time
          cp -r ./utils-time/validate.c ./${{ env.OUTPUT_FOLDER }}/utils/time/
          cp -r ./utils-time/validate.h ./${{ env.OUTPUT_FOLDER }}/utils/time/
          
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/drivers/rtc/mcp7940
          cp ./mcp7940.c ./${{ env.OUTPUT_FOLDER }}/drivers/rtc/mcp7940/
          cp ./mcp7940.h ./${{ env.OUTPUT_FOLDER }}/drivers/rtc/mcp7940/
 
      - name: Pack files for upload
        run: |
          tar -czvf build.tar.gz ${{ env.OUTPUT_FOLDER }}
          zip -r build.zip ${{ env.OUTPUT_FOLDER }}

      - name: Upload library package
        uses: actions/upload-artifact@v4
        with:
            name: library-package
            path: ${{ env.OUTPUT_FOLDER }}
            retention-days: 1